### ISSUE TITLE
सू॑क्तानां देवता-ऋषि-च्छन्दां॑सि

### ISSUE THREAD

**Issue by ujjvlh** [vishvAsa/vedAH_Rk#1]
सू॑क्तानां देवता-ऋषि-च्छन्दां॑सि कु॑त्र सं॑गृहीतानि अस्मि॑न्?

**Comment by vvasuki** [comment]
प्रतिमन्त्रं निर्दिष्टम्। यथा - https://github.com/vishvAsa/vedAH_Rk/blob/static_files/shAkalam/saMhitA/sarvASh_TIkAH/01/002/01_vAyavA_yAhi.md इत्यत्र "अधिमन्त्रम्" इति भागे वीक्षताम्।

**Comment by ujjvlh** [comment]
> प्रतिमन्त्रं निर्दिष्टम्। यथा - https://github.com/vishvAsa/vedAH_Rk/blob/static_files/shAkalam/saMhitA/sarvASh_TIkAH/01/002/01_vAyavA_yAhi.md इत्यत्र "अधिमन्त्रम्" इति भागे वीक्षताम्।

अ॑नुगृहीतोऽस्मि 🙏
